name: check

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Show flake outputs
        run: nix flake show

      - name: Run flake check
        run: nix flake check --print-build-logs
